export const shipmentData = [
  {
    shipmentID: "123234554",
    pickupLocation: "Ikeja, Lagos",
    pickupDetails: "Pickup by 5pm today",
    deliveryLocation: "Otta, Ogun State",
    deliveryDetails: "Expected delivery in 3 days",
    ownerName: "Mr Khalid",
    truck: "Truck1",
    price: "200K",
  },
  {
    shipmentID: "123222254",
    pickupLocation: "Iyana-Ipaja, Lagos",
    pickupDetails: "Pickup by 5pm today",
    deliveryLocation: "Otta, Ogun State",
    deliveryDetails: "Expected delivery in 2 days",
    ownerName: "Mr John",
    truck: "Truck4",
    price: "300K",
  },
  {
    shipmentID: "980234554",
    pickupLocation: "Ojo, Lagos",
    pickupDetails: "Pickup by 5pm today",
    deliveryLocation: "Otta, Ogun State",
    deliveryDetails: "Expected delivery in 2 days",
    ownerName: "Mr John",
    truck: "Truck6",
    price: "250K",
  },
  {
    shipmentID: "123889754",
    pickupLocation: "Surulere, Lagos",
    pickupDetails: "Pickup by 5pm today",
    deliveryLocation: "Otta, Ogun State",
    deliveryDetails: "Expected delivery in 3 days",
    ownerName: "Mr Matt",
    truck: "Truck5",
    price: "400K",
  },
];